### ISSUE TITLE
windows 11 下载启动报错

### ISSUE THREAD

**Issue by shihzenq** [WangRongsheng/XrayGLM#18]
先安装命令
pip install -i https://mirrors.aliyun.com/pypi/simple/ -r requirements_wo_ds.txt
pip install -i https://mirrors.aliyun.com/pypi/simple/ --no-deps "SwissArmyTransformer>=0.3.6"

后下载模型是：XrayGLM-300

启动命令： python web_demo.py --from_pretrained checkpoints/checkpoints-XrayGLM-300
发生错误：
PS F:\GML\XrayGLM> python web_demo.py --from_pretrained checkpoints/checkpoints-XrayGLM-300
[2023-06-05 00:00:17,422] [INFO] DeepSpeed/CUDA is not installed, fallback to Pytorch checkpointing.
[2023-06-05 00:00:17,493] [WARNING] DeepSpeed Not Installed, you cannot import training_main from sat now.
Traceback (most recent call last):
  File "F:\GML\XrayGLM\web_demo.py", line 12, in <module>
    from finetune_XrayGLM import FineTuneVisualGLMModel
  File "F:\GML\XrayGLM\finetune_XrayGLM.py", line 6, in <module>
    from sat.training.deepspeed_training import training_main
  File "C:\Users\1\AppData\Local\Programs\Python\Python39\lib\site-packages\sat\training\deepspeed_training.py", line 27, in <module>
    import deepspeed
ModuleNotFoundError: No module named 'deepspeed'

**Comment by WangRongsheng** [comment]
您好，我们经过尝试也是同样的问题，为此我们给出以下建议：
- 在[VisualGLM-6B/issues](https://github.com/THUDM/VisualGLM-6B/issues) 询问如何解决，相信ViusalGLM他们debug经验会更丰富；
- 可以尝试使用[cli_demo_hf.py](https://github.com/THUDM/VisualGLM-6B/blob/main/cli_demo_hf.py) 进行推理，这样应该就不会用到deepspeed；

**Comment by shihzenq** [comment]
下载的XrayGLM 源码里没有cli_demo_hf.py

**Comment by WangRongsheng** [comment]
可以在https://github.com/THUDM/VisualGLM-6B repo里面获得。

**Comment by shihzenq** [comment]
您的意思，我直接用[VisualGLM-6B]，不用XrayGLM了吗

**Comment by WangRongsheng** [comment]
> 您的意思，我直接用[VisualGLM-6B]，不用XrayGLM了吗

两个项目的代码是不存在冲突的。

**Comment by shihzenq** [comment]
王老师，那我用VisualGLM-6B能运行您的模型吗？比如这个XrayGLM-300

**Comment by WangRongsheng** [comment]
> 王老师，那我用VisualGLM-6B能运行您的模型吗？比如这个XrayGLM-300

可以的
