### ISSUE TITLE
Deepspeed没法跳过

### ISSUE THREAD

**Issue by basakamars** [WangRongsheng/XrayGLM#38]
# 安装依赖
pip install -i https://mirrors.aliyun.com/pypi/simple/ -r requirements_wo_ds.txt
# 安装SwissArmyTransformer
pip install -i https://mirrors.aliyun.com/pypi/simple/ --no-deps "SwissArmyTransformer>=0.3.6"
已经用按照你的方法安装，但依然显示缺少这个模块。并且这个模块在windows11上无法安装。

Traceback (most recent call last):
  File "D:\XrayGLM\web_demo.py", line 12, in <module>
    from finetune_XrayGLM import FineTuneVisualGLMModel
  File "D:\XrayGLM\finetune_XrayGLM.py", line 6, in <module>
    from sat.training.deepspeed_training import training_main
  File "D:\XrayGLM\venv\lib\site-packages\sat\training\deepspeed_training.py", line 27, in <module>
    import deepspeed
ModuleNotFoundError: No module named 'deepspeed'

**Comment by basakamars** [comment]
# 问题已经解决
## 修改文件
finetune_XrayGLM.py
```python
import os
import torch
import argparse


from sat import mpu, get_args, get_tokenizer
from sat.training.deepspeed_training import training_main  #把这行注释掉即可。
from model import VisualGLMModel
```
