### ISSUE TITLE
finetune_XrayGLM.py 加载sat 模型时出现错误

### ISSUE THREAD

**Issue by sincerity-being** [WangRongsheng/XrayGLM#45]
finetune_XrayGLM.py文件中的第178行
 model_type = 'visualglm-6b'
 model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args)
加载sat库中的模型时报错
Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/dawnlab/.sat_models/visualglm-6b.zip ...
/home/dawnlab/.sat_models/visualglm-6b.zip: 100%|██████████| 41.8k/41.8k [00:00<00:00, 6.84MB/s]
Unzipping /home/dawnlab/.sat_models/visualglm-6b.zip...
python-BaseException
Traceback (most recent call last):
  File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/site-packages/sat/resources/download.py", line 65, in auto_create
    f = zipfile.ZipFile(file_path, 'r')
  File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by sujaly** [comment]
同问，我也遇到了这个问题，大家是怎么解决的？

**Comment by sujaly** [comment]
检查发现是https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 对应的visualglm-6b.zip缺失了，

**Comment by zyywansui123** [comment]
同问

**Comment by TaylorRex** [comment]
同问

**Comment by yihp** [comment]
@sujaly @zyywansui123 @sincerity-being 请问解决了吗，我也遇到了这个问题

**Comment by sujaly** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by chindeng** [comment]
我也遇到这个问题，请问是否可以解决？还是说要自己下一个

**Comment by sujaly** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by CaiCaidn** [comment]
请问有什么办法解决吗

**Comment by sujaly** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by sujaly** [comment]
重新安装环境就行了&nbsp;


苏话说
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月26日(星期一) 下午4:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WangRongsheng/XrayGLM] finetune_XrayGLM.py 加载sat 模型时出现错误 (Issue #45)





 
请问有什么办法解决吗

**Comment by MrHZF** [comment]
> 重新安装环境就行了&nbsp; 苏话说 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年2月26日(星期一) 下午4:25 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [WangRongsheng/XrayGLM] finetune_XrayGLM.py 加载sat 模型时出现错误 (Issue #45) 请问有什么办法解决吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

请问解决了吗

**Comment by sujaly** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by DongnuanCai** [comment]
> > 重新安装环境就行了  苏话说 _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2024年2月26日(星期一) 下午4:25 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [WangRongsheng/XrayGLM] finetune_XrayGLM.py 加载sat 模型时出现错误 (Issue #45) 请问有什么办法解决吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> 请问解决了吗

更新visualglm新的下载地址或者将权重下载到本地就可以了

**Comment by MrHZF** [comment]
> > > 重新安装环境就行了  苏话说 _**@**_.***  
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2024年2月26日(星期一) 下午4:25 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [WangRongsheng/XrayGLM] finetune_XrayGLM.py 加载sat 模型时出现错误 (Issue #45) 请问有什么办法解决吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> > 
> > 
> > 请问解决了吗
> 
> 更新visualglm新的下载地址或者将权重下载到本地就可以了

请问是将huagging face 上的模型和权重全都下载下来吗？

**Comment by DongnuanCai** [comment]
> > > > 重新安装环境就行了  苏话说 _**@**_.***  
> > > > […](#)
> > > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2024年2月26日(星期一) 下午4:25 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [WangRongsheng/XrayGLM] finetune_XrayGLM.py 加载sat 模型时出现错误 (Issue #45) 请问有什么办法解决吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> > > 
> > > 
> > > 请问解决了吗
> > 
> > 
> > 更新visualglm新的下载地址或者将权重下载到本地就可以了
> 
> 请问是将huagging face 上的模型和权重全都下载下来吗？

你可以参考visualglm下的issues，有相同问题的解决方案，可以把权重下到本地，也可以修改权重下载链接，因为原来的链接失效了

**Comment by JackHeroFly** [comment]
> finetune_XrayGLM.py文件中的第178行 model_type = 'visualglm-6b' model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args) 加载sat库中的模型时报错 Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/dawnlab/.sat_models/visualglm-6b.zip ... /home/dawnlab/.sat_models/visualglm-6b.zip: 100%|██████████| 41.8k/41.8k [00:00<00:00, 6.84MB/s] Unzipping /home/dawnlab/.sat_models/visualglm-6b.zip... python-BaseException Traceback (most recent call last): File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/site-packages/sat/resources/download.py", line 65, in auto_create f = zipfile.ZipFile(file_path, 'r') File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1269, in **init** self._RealGetContents() File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1336, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file

您好，请问这个问题你解决了吗？我也遇到了这个问题，请教。

**Comment by sujaly** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by DongnuanCai** [comment]
> > finetune_XrayGLM.py文件中的第178行 model_type = 'visualglm-6b' model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args) 加载sat库中的模型时报错 Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/dawnlab/.sat_models/visualglm-6b.zip ... /home/dawnlab/.sat_models/visualglm-6b.zip: 100%|██████████| 41.8k/41.8k [00:00<00:00, 6.84MB/s] Unzipping /home/dawnlab/.sat_models/visualglm-6b.zip... python-BaseException Traceback (most recent call last): File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/site-packages/sat/resources/download.py", line 65, in auto_create f = zipfile.ZipFile(file_path, 'r') File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1269, in **init** self._RealGetContents() File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1336, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
> 
> 您好，请问这个问题你解决了吗？我也遇到了这个问题，请教。

可以参考可以参考visualglm下的issues，有相同问题的解决方案，可以把权重下到本地，也可以修改权重下载链接，因为原来的链接失效了

**Comment by DongnuanCai** [comment]
> > finetune_XrayGLM.py文件中的第178行 model_type = 'visualglm-6b' model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args) 加载sat库中的模型时报错 Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/dawnlab/.sat_models/visualglm-6b.zip ... /home/dawnlab/.sat_models/visualglm-6b.zip: 100%|██████████| 41.8k/41.8k [00:00<00:00, 6.84MB/s] Unzipping /home/dawnlab/.sat_models/visualglm-6b.zip... python-BaseException Traceback (most recent call last): File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/site-packages/sat/resources/download.py", line 65, in auto_create f = zipfile.ZipFile(file_path, 'r') File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1269, in **init** self._RealGetContents() File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1336, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
> 
> 您好，请问这个问题你解决了吗？我也遇到了这个问题，请教。

可以参考visualglm下的issues，有相同问题的解决方案，可以把权重下到本地，也可以修改权重下载链接，因为原来的链接失效了

**Comment by JackHeroFly** [comment]
> > > finetune_XrayGLM.py文件中的第178行 model_type = 'visualglm-6b' model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args) 加载sat库中的模型时报错 Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/dawnlab/.sat_models/visualglm-6b.zip ... /home/dawnlab/.sat_models/visualglm-6b.zip: 100%|██████████| 41.8k/41.8k [00:00<00:00, 6.84MB/s] Unzipping /home/dawnlab/.sat_models/visualglm-6b.zip... python-BaseException Traceback (most recent call last): File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/site-packages/sat/resources/download.py", line 65, in auto_create f = zipfile.ZipFile(file_path, 'r') File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1269, in **init** self._RealGetContents() File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1336, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
> > 
> > 
> > 您好，请问这个问题你解决了吗？我也遇到了这个问题，请教。
> 
> 可以参考visualglm下的issues，有相同问题的解决方案，可以把权重下到本地，也可以修改权重下载链接，因为原来的链接失效了
非常谢谢您，我试试看，是否可以加您的qq？大模型学习交流使用。

**Comment by DongnuanCai** [comment]
> > > > finetune_XrayGLM.py文件中的第178行 model_type = 'visualglm-6b' model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args) 加载sat库中的模型时报错 Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/dawnlab/.sat_models/visualglm-6b.zip ... /home/dawnlab/.sat_models/visualglm-6b.zip: 100%|██████████| 41.8k/41.8k [00:00<00:00, 6.84MB/s] Unzipping /home/dawnlab/.sat_models/visualglm-6b.zip... python-BaseException Traceback (most recent call last): File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/site-packages/sat/resources/download.py", line 65, in auto_create f = zipfile.ZipFile(file_path, 'r') File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1269, in **init** self._RealGetContents() File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1336, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
> > > 
> > > 
> > > 您好，请问这个问题你解决了吗？我也遇到了这个问题，请教。
> > 
> > 
> > 可以参考visualglm下的issues，有相同问题的解决方案，可以把权重下到本地，也可以修改权重下载链接，因为原来的链接失效了
> > 非常谢谢您，我试试看，是否可以加您的qq？大模型学习交流使用。

不必称呼为您，在大模型方面我接触到的东西也是非常少，可能没办法与你进行更多的交流，仅是基于兴趣跑了这个开源的模型，如果没有找到对应的issues，可以试试更新visualglm的model文件，在visualglm-6b仓库已经进行了链接的更新，如果还是没办法跑通可能无法提供更多的建议了，我当时遇到的问题主要就是这个，祝顺利。

**Comment by ahijian** [comment]
> > > > > finetune_XrayGLM.py文件中的第178行 model_type = 'visualglm-6b' model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args) 加载sat库中的模型时报错 Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/dawnlab/.sat_models/visualglm-6b.zip ... /home/dawnlab/.sat_models/visualglm-6b.zip: 100%|██████████| 41.8k/41.8k [00:00<00:00, 6.84MB/s] Unzipping /home/dawnlab/.sat_models/visualglm-6b.zip... python-BaseException Traceback (most recent call last): File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/site-packages/sat/resources/download.py", line 65, in auto_create f = zipfile.ZipFile(file_path, 'r') File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1269, in **init** self._RealGetContents() File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1336, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
> > > > 
> > > > 
> > > > 您好，请问这个问题你解决了吗？我也遇到了这个问题，请教。
> > > 
> > > 
> > > 可以参考visualglm下的issues，有相同问题的解决方案，可以把权重下到本地，也可以修改权重下载链接，因为原来的链接失效了
> > > 非常谢谢您，我试试看，是否可以加您的qq？大模型学习交流使用。
> 
> 不必称呼为您，在大模型方面我接触到的东西也是非常少，可能没办法与你进行更多的交流，仅是基于兴趣跑了这个开源的模型，如果没有找到对应的issues，可以试试更新visualglm的model文件，在visualglm-6b仓库已经进行了链接的更新，如果还是没办法跑通可能无法提供更多的建议了，我当时遇到的问题主要就是这个，祝顺利。

你好，我按照你说的更行了model,确实可以下载visualglm-6b了，但是报出如下错误“Unable to load optimizer from checkpoint E:\此处省略...\chatglm-6b\visualglm-6b\1\mp_rank_00_model_states.pt, exiting. Specify --no-load-rng or --finetune to prevent attempting to load the random state."你遇到过这个问题吗？

**Comment by ahijian** [comment]
> > > > > finetune_XrayGLM.py文件中的第178行 model_type = 'visualglm-6b' model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args) 加载sat库中的模型时报错 Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/dawnlab/.sat_models/visualglm-6b.zip ... /home/dawnlab/.sat_models/visualglm-6b.zip: 100%|██████████| 41.8k/41.8k [00:00<00:00, 6.84MB/s] Unzipping /home/dawnlab/.sat_models/visualglm-6b.zip... python-BaseException Traceback (most recent call last): File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/site-packages/sat/resources/download.py", line 65, in auto_create f = zipfile.ZipFile(file_path, 'r') File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1269, in **init** self._RealGetContents() File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1336, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
> > > > 
> > > > 
> > > > 您好，请问这个问题你解决了吗？我也遇到了这个问题，请教。
> > > 
> > > 
> > > 可以参考visualglm下的issues，有相同问题的解决方案，可以把权重下到本地，也可以修改权重下载链接，因为原来的链接失效了
> > > 非常谢谢您，我试试看，是否可以加您的qq？大模型学习交流使用。
> 
> 不必称呼为您，在大模型方面我接触到的东西也是非常少，可能没办法与你进行更多的交流，仅是基于兴趣跑了这个开源的模型，如果没有找到对应的issues，可以试试更新visualglm的model文件，在visualglm-6b仓库已经进行了链接的更新，如果还是没办法跑通可能无法提供更多的建议了，我当时遇到的问题主要就是这个，祝顺利。

你好，我按照你说的更行了model,确实可以下载visualglm-6b了，但是报出如下错误“Unable to load optimizer from checkpoint E:\此处省略...\chatglm-6b\visualglm-6b\1\mp_rank_00_model_states.pt, exiting. Specify --no-load-rng or --finetune to prevent attempting to load the random state."你遇到过这个问题吗？

**Comment by ahijian** [comment]
> > > > > finetune_XrayGLM.py文件中的第178行 model_type = 'visualglm-6b' model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args) 加载sat库中的模型时报错 Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/dawnlab/.sat_models/visualglm-6b.zip ... /home/dawnlab/.sat_models/visualglm-6b.zip: 100%|██████████| 41.8k/41.8k [00:00<00:00, 6.84MB/s] Unzipping /home/dawnlab/.sat_models/visualglm-6b.zip... python-BaseException Traceback (most recent call last): File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/site-packages/sat/resources/download.py", line 65, in auto_create f = zipfile.ZipFile(file_path, 'r') File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1269, in **init** self._RealGetContents() File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1336, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
> > > > 
> > > > 
> > > > 您好，请问这个问题你解决了吗？我也遇到了这个问题，请教。
> > > 
> > > 
> > > 可以参考visualglm下的issues，有相同问题的解决方案，可以把权重下到本地，也可以修改权重下载链接，因为原来的链接失效了
> > > 非常谢谢您，我试试看，是否可以加您的qq？大模型学习交流使用。
> 
> 不必称呼为您，在大模型方面我接触到的东西也是非常少，可能没办法与你进行更多的交流，仅是基于兴趣跑了这个开源的模型，如果没有找到对应的issues，可以试试更新visualglm的model文件，在visualglm-6b仓库已经进行了链接的更新，如果还是没办法跑通可能无法提供更多的建议了，我当时遇到的问题主要就是这个，祝顺利。

你好，我按照你说的更行了model,确实可以下载visualglm-6b了，但是报出如下错误“Unable to load optimizer from checkpoint E:\此处省略...\chatglm-6b\visualglm-6b\1\mp_rank_00_model_states.pt, exiting. Specify --no-load-rng or --finetune to prevent attempting to load the random state."你遇到过这个问题吗？

**Comment by DongnuanCai** [comment]
> > > > > > finetune_XrayGLM.py文件中的第178行 model_type = 'visualglm-6b' model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args) 加载sat库中的模型时报错 Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/dawnlab/.sat_models/visualglm-6b.zip ... /home/dawnlab/.sat_models/visualglm-6b.zip: 100%|██████████| 41.8k/41.8k [00:00<00:00, 6.84MB/s] Unzipping /home/dawnlab/.sat_models/visualglm-6b.zip... python-BaseException Traceback (most recent call last): File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/site-packages/sat/resources/download.py", line 65, in auto_create f = zipfile.ZipFile(file_path, 'r') File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1269, in **init** self._RealGetContents() File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1336, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
> > > > > 
> > > > > 
> > > > > 您好，请问这个问题你解决了吗？我也遇到了这个问题，请教。
> > > > 
> > > > 
> > > > 可以参考visualglm下的issues，有相同问题的解决方案，可以把权重下到本地，也可以修改权重下载链接，因为原来的链接失效了
> > > > 非常谢谢您，我试试看，是否可以加您的qq？大模型学习交流使用。
> > 
> > 
> > 不必称呼为您，在大模型方面我接触到的东西也是非常少，可能没办法与你进行更多的交流，仅是基于兴趣跑了这个开源的模型，如果没有找到对应的issues，可以试试更新visualglm的model文件，在visualglm-6b仓库已经进行了链接的更新，如果还是没办法跑通可能无法提供更多的建议了，我当时遇到的问题主要就是这个，祝顺利。
> 
> 你好，我按照你说的更行了model,确实可以下载visualglm-6b了，但是报出如下错误“Unable to load optimizer from checkpoint E:\此处省略...\chatglm-6b\visualglm-6b\1\mp_rank_00_model_states.pt, exiting. Specify --no-load-rng or --finetune to prevent attempting to load the random state."你遇到过这个问题吗？

可能是些许环境问题我之前好像也遇到过，但具体记不大清了，你去看我fork的仓库里的一个笔记本吧，我之前跑通时也调整了一些库的版本，应该是能够跑通的那个文件，可能有些操作也是比较冗余的，其他的可能没办法提供更多建议了。

**Comment by ahijian** [comment]
> fork的仓库里的一个笔记本

谢谢你，你fork仓库里的笔记本是那个文件呢？没找到这个文件

**Comment by ahijian** [comment]
> > > > > > > finetune_XrayGLM.py文件中的第178行 model_type = 'visualglm-6b' model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args) 加载sat库中的模型时报错 Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/dawnlab/.sat_models/visualglm-6b.zip ... /home/dawnlab/.sat_models/visualglm-6b.zip: 100%|██████████| 41.8k/41.8k [00:00<00:00, 6.84MB/s] Unzipping /home/dawnlab/.sat_models/visualglm-6b.zip... python-BaseException Traceback (most recent call last): File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/site-packages/sat/resources/download.py", line 65, in auto_create f = zipfile.ZipFile(file_path, 'r') File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1269, in **init** self._RealGetContents() File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1336, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
> > > > > > 
> > > > > > 
> > > > > > 您好，请问这个问题你解决了吗？我也遇到了这个问题，请教。
> > > > > 
> > > > > 
> > > > > 可以参考visualglm下的issues，有相同问题的解决方案，可以把权重下到本地，也可以修改权重下载链接，因为原来的链接失效了
> > > > > 非常谢谢您，我试试看，是否可以加您的qq？大模型学习交流使用。
> > > 
> > > 
> > > 不必称呼为您，在大模型方面我接触到的东西也是非常少，可能没办法与你进行更多的交流，仅是基于兴趣跑了这个开源的模型，如果没有找到对应的issues，可以试试更新visualglm的model文件，在visualglm-6b仓库已经进行了链接的更新，如果还是没办法跑通可能无法提供更多的建议了，我当时遇到的问题主要就是这个，祝顺利。
> > 
> > 
> > 你好，我按照你说的更行了model,确实可以下载visualglm-6b了，但是报出如下错误“Unable to load optimizer from checkpoint E:\此处省略...\chatglm-6b\visualglm-6b\1\mp_rank_00_model_states.pt, exiting. Specify --no-load-rng or --finetune to prevent attempting to load the random state."你遇到过这个问题吗？
> 
> 可能是些许环境问题我之前好像也遇到过，但具体记不大清了，你去看我fork的仓库里的一个笔记本吧，我之前跑通时也调整了一些库的版本，应该是能够跑通的那个文件，可能有些操作也是比较冗余的，其他的可能没办法提供更多建议了。

谢谢你，你fork仓库里的笔记本是那个文件呢？没找到这个文件

**Comment by DongnuanCai** [comment]
> > > > > > > > finetune_XrayGLM.py文件中的第178行 model_type = 'visualglm-6b' model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args) 加载sat库中的模型时报错 Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/dawnlab/.sat_models/visualglm-6b.zip ... /home/dawnlab/.sat_models/visualglm-6b.zip: 100%|██████████| 41.8k/41.8k [00:00<00:00, 6.84MB/s] Unzipping /home/dawnlab/.sat_models/visualglm-6b.zip... python-BaseException Traceback (most recent call last): File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/site-packages/sat/resources/download.py", line 65, in auto_create f = zipfile.ZipFile(file_path, 'r') File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1269, in **init** self._RealGetContents() File "/home/dawnlab/anaconda3/envs/glm/lib/python3.8/zipfile.py", line 1336, in _RealGetContents raise BadZipFile("File is not a zip file") zipfile.BadZipFile: File is not a zip file
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，请问这个问题你解决了吗？我也遇到了这个问题，请教。
> > > > > > 
> > > > > > 
> > > > > > 可以参考visualglm下的issues，有相同问题的解决方案，可以把权重下到本地，也可以修改权重下载链接，因为原来的链接失效了
> > > > > > 非常谢谢您，我试试看，是否可以加您的qq？大模型学习交流使用。
> > > > 
> > > > 
> > > > 不必称呼为您，在大模型方面我接触到的东西也是非常少，可能没办法与你进行更多的交流，仅是基于兴趣跑了这个开源的模型，如果没有找到对应的issues，可以试试更新visualglm的model文件，在visualglm-6b仓库已经进行了链接的更新，如果还是没办法跑通可能无法提供更多的建议了，我当时遇到的问题主要就是这个，祝顺利。
> > > 
> > > 
> > > 你好，我按照你说的更行了model,确实可以下载visualglm-6b了，但是报出如下错误“Unable to load optimizer from checkpoint E:\此处省略...\chatglm-6b\visualglm-6b\1\mp_rank_00_model_states.pt, exiting. Specify --no-load-rng or --finetune to prevent attempting to load the random state."你遇到过这个问题吗？
> > 
> > 
> > 可能是些许环境问题我之前好像也遇到过，但具体记不大清了，你去看我fork的仓库里的一个笔记本吧，我之前跑通时也调整了一些库的版本，应该是能够跑通的那个文件，可能有些操作也是比较冗余的，其他的可能没办法提供更多建议了。
> 
> 谢谢你，你fork仓库里的笔记本是那个文件呢？没找到这个文件

xrayglm的notebook文件
