### ISSUE TITLE
BadZipFile: File is not a zip file”

### ISSUE THREAD

**Issue by JackHeroFly** [WangRongsheng/XrayGLM#82]
您好，作者，我按照您说的微调步骤，运行finetune_XrayGLM.py时，报出如下错误：
“”C:\Users\B424/.sat_models\visualglm-6b.zip: 100%|██████████| 16.7k/16.7k [00:00<00:00, 8.38MB/s]Unzipping C:\Users\B424/.sat_models\visualglm-6b.zip...

Traceback (most recent call last):

  File D:\anancondanzhuang\envs\th-gpu-BM\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File f:\xumaterial\xu_csc\xu_csc_c-f-r-s\xu_csc_all_materials_14bm\7xrayglm\xrayglm-main\finetune_xrayglm.py:178
    model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args)

  File D:\anancondanzhuang\envs\th-gpu-BM\lib\site-packages\sat\model\base_model.py:215 in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)

  File D:\anancondanzhuang\envs\th-gpu-BM\lib\site-packages\sat\model\base_model.py:201 in from_pretrained_base
    model_path = auto_create(name, path=home_path, url=url)

  File D:\anancondanzhuang\envs\th-gpu-BM\lib\site-packages\sat\resources\download.py:74 in auto_create
    f = zipfile.ZipFile(file_path, 'r')

  File D:\anancondanzhuang\envs\th-gpu-BM\lib\zipfile.py:1258 in __init__
    self._RealGetContents()

  File D:\anancondanzhuang\envs\th-gpu-BM\lib\zipfile.py:1325 in _RealGetContents
    raise BadZipFile("File is not a zip file")

BadZipFile: File is not a zip file”
，为什么无法下载visualglm-6b.zip文件呢？该如何解决

**Comment by huqinjie** [comment]
Downloading models https://cloud.tsinghua.edu.cn/f/348b98dffcc940b6a09d/?dl=1 into /home/camerart/.sat_models ...
/home/camerart/.sat_models/visualglm-6b.zip: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16.7k/16.7k [00:00<00:00, 14.9MB/s]
Unzipping /home/camerart/.sat_models/visualglm-6b.zip...
Traceback (most recent call last):
  File "finetune_XrayGLM.py", line 188, in <module>
    model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args)
  File "/home/camerart/anaconda3/envs/XrayGLM/lib/python3.8/site-packages/sat/model/base_model.py", line 217, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/home/camerart/anaconda3/envs/XrayGLM/lib/python3.8/site-packages/sat/model/base_model.py", line 202, in from_pretrained_base
    model_path = auto_create(name, path=home_path, url=url)
  File "/home/camerart/anaconda3/envs/XrayGLM/lib/python3.8/site-packages/sat/resources/download.py", line 74, in auto_create
    f = zipfile.ZipFile(file_path, 'r')
  File "/home/camerart/anaconda3/envs/XrayGLM/lib/python3.8/zipfile.py", line 1271, in __init__
    self._RealGetContents()
  File "/home/camerart/anaconda3/envs/XrayGLM/lib/python3.8/zipfile.py", line 1338, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-08-31 01:28:29,754] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 19491
我也遇到了类似的问题

**Comment by GuGuGuGun** [comment]
换成MODEL_URLS['visualglm-6b'] = 'r2://visualglm-6b.zip'

**Comment by xianming-gu** [comment]
> 换成MODEL_URLS['visualglm-6b'] = 'r2://visualglm-6b.zip'

你好 请问可以提供一下visualglm-6b.zip文件吗 感谢
